# The language specific base vm to use for this repository
language: node_js

# The node.js version to install
node_js: "0.12.7"

install:
  # Install meteor
  - "curl https://install.meteor.com | /bin/sh"
  # Install spacejam
  - "npm install -g spacejam"

# For testing meteor packages, that's all that is needed. 
script:
  - "spacejam test-packages ./"