# The language specific base vm to use for this repository
language: node_js

# The node.js version to install
node_js: "0.12.7"

install:
  # Install meteor
  - "curl https://install.meteor.com | /bin/sh"
  # Adding meteor to the $PATH
  - "export PATH=$HOME/.meteor:$PATH"
  # Copy the settings_sample.js file to settings.js
  - "cp _config/settings_sample.js _config/settings.js"
  # Install spacejam
  - "npm install spacejam"

# For testing meteor packages, that's all that is needed. 
script:
  - "node_modules/.bin/spacejam test-packages ./ --settings settings.json"